#!/usr/bin/env bash
# Make `import pairs_teardown` work from the venv (notebooks, Jupyter kernels,
# scripts, plain `python`) no matter what uv/macOS does to the hidden flag.
#
# Why this is needed: macOS sets the UF_HIDDEN flag on the venv and the files uv
# writes into it, and CPython 3.12's `site` module silently skips hidden `.pth`
# files — so uv's editable-install `.pth` is ignored and the package can't be
# imported. uv re-hides the whole `.venv` tree on every sync/reinstall, so a
# `.pth`-based fix keeps breaking.
#
# The durable fix is a `sitecustomize.py` in site-packages: Python auto-imports
# it at startup, and regular module import is NOT filtered by UF_HIDDEN (only
# `.pth` processing is). So it works even when everything in the venv is hidden
# and even when no PYTHONPATH is set — which covers the VS Code auto-discovered
# `.venv` kernel. Idempotent; run after `rm -rf .venv && uv sync --extra dev`.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV="$REPO_ROOT/.venv"

if [[ ! -d "$VENV" ]]; then
  echo "No .venv found. Run 'uv sync --extra dev' first." >&2
  exit 1
fi

# Clear the hidden flag (nice-to-have; the sitecustomize fix below does not
# depend on it, but it keeps `uv run` and .pth-based tools happy too).
chflags -R nohidden "$VENV" || true

SITE_PACKAGES="$(find "$VENV/lib" -maxdepth 2 -name site-packages -type d | head -1)"

# The bulletproof mechanism: auto-imported at every interpreter startup,
# immune to the hidden flag, needs no PYTHONPATH.
cat > "$SITE_PACKAGES/sitecustomize.py" <<EOF
# Auto-generated by scripts/fix_venv.sh — puts the project source on sys.path
# regardless of the venv's macOS hidden flag. Safe to delete.
import sys

_SRC = "$REPO_ROOT/src"
if _SRC not in sys.path:
    sys.path.insert(0, _SRC)
EOF

echo "Wrote: $SITE_PACKAGES/sitecustomize.py -> $REPO_ROOT/src"
env -i "$VENV/bin/python" -c "import pairs_teardown; print('import pairs_teardown OK')"
